language: rust
rust:
  - nightly
services:
  - postgresql
env:
  - DATABASE_URL=postgres://osc:stallman@db/osc
before_script:
  - rustup component add rustfmt-preview
  - psql -c 'create database osc;' -U postgres
script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test -- --test-threads=1
cache: cargo
