version: '3'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/club-backend
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=osc
      - POSTGRES_PASSWORD=stallman
