version: '3'

services:
  backend:
    build: .
    environment:
      - DATABASE_URL=postgres://osc:stallman@db/osc
    volumes:
      - .:/usr/src/backend
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=osc
      - POSTGRES_PASSWORD=stallman
